"""
sabian_symbols.py
=================
* NOTE: Reference data for Sabian Symbols (360 degrees) and Decan-Tarot mapping.
  Sabian Symbols are 1-indexed (degree 0°00'-0°59' of Aries = Symbol 1).
  We use a curated subset of the original Marc Edmund Jones / Dane Rudhyar symbols.

! IMPORTANT: These are condensed interpretive phrases, not the full
  paragraph-length Rudhyar descriptions.
"""

# ----------------------------------------------------------------
# Sabian Symbols: 360 entries (index 0 = Aries 1°, index 359 = Pisces 30°)
# Source: Condensed from Dane Rudhyar's "An Astrological Mandala"
# ----------------------------------------------------------------
SABIAN_SYMBOLS = [
    # --- ARIES (0-29) ---
    "A woman just risen from the sea; a seal embraces her.",
    "A comedian entertaining a group of friends.",
    "A cameo profile of a man in the outline of his country.",
    "Two lovers strolling on a secluded walk.",
    "A triangle with wings.",
    "A square brightly lighted on one side.",
    "A man successfully expressing himself in two realms at once.",
    "A large woman's hat with streamers blown by an east wind.",
    "A crystal gazer.",
    "A teacher gives new symbolic forms to traditional images.",
    "The president of the country.",
    "A flock of wild geese.",
    "A bomb which failed to explode is now safely concealed.",
    "A serpent coiling near a man and a woman.",
    "An Indian weaving a ceremonial blanket.",
    "Brownies dancing in the setting sun.",
    "Two dignified spinsters sitting in silence.",
    "An empty hammock stretched between two trees.",
    "The magic carpet of oriental imagery.",
    "A young girl feeding birds in winter.",
    "A pugilist enters the ring.",
    "The gate to the garden of all fulfilled desires.",
    "A pregnant woman in light summer dress.",
    "An open window and a net curtain blowing into a cornucopia.",
    "A double promise reveals its inner and outer meanings.",
    "A man possessed of more gifts than he can hold.",
    "Through imagination a lost opportunity is regained.",
    "A large audience confronts the performer.",
    "A celestial choir singing.",
    "A duck pond and its brood.",
    # --- TAURUS (30-59) ---
    "A clear mountain stream.",
    "An electrical storm.",
    "Steps up to a lawn of clover in bloom.",
    "A pot of gold at the end of the rainbow.",
    "A widow at an open grave.",
    "A bridge being built across a gorge.",
    "A woman of Samaria at the ancestral well.",
    "A woman holding a lighted candle in a three-fingered hand.",
    "A sleigh on land uncovered by snow.",
    "A Red Cross nurse.",
    "A woman sprinkling long rows of flowers.",
    "A white dove flying over troubled waters.",
    "Porter carrying heavy baggage.",
    "A man on a magic carpet hovers over a large area of land.",
    "The crucifixion.",
    "An old teacher fails to interest pupils in traditional knowledge.",
    "An indian warrior riding fiercely, human scalps hanging from his belt.",
    "A woman in middle life stands in rapt sudden realization of forgotten charms.",
    "A new continent rising majestically from the ocean.",
    "A bridge built of gold-colored bricks.",
    "A peacock parading on an ancient lawn.",
    "A road through enchanted hills.",
    "Head of health bureau unable to cope with an epidemic.",
    "Tiny snowflakes drifting across a white landscape.",
    "A vast public park.",
    "A Spaniard serenading his señorita.",
    "An Indian squaw pleading to the chief for the lives of her children.",
    "A woman past her prime courageously faces a seemingly empty life.",
    "Two cobblers working at a table.",
    "A naturalist lecturing, using a model of the earth.",
    # --- GEMINI (60-89) ---
    "A glass-bottomed boat reveals undersea wonders.",
    "Santa Claus furtively filling stockings hanging in front of a fireplace.",
    "The garden of the Tuileries in Paris.",
    "A cafeteria with an abundance of choices.",
    "A revolutionary magazine asking for action.",
    "Workmen drilling for oil.",
    "An old-fashioned well.",
    "A beautiful woman, muffled in fur is leading a small dog on a leash.",
    "A quiver filled with arrows.",
    "An airplane performing a nose dive.",
    "Newly opened lands offer the pioneer new opportunities for experience.",
    "An African child plays with white children.",
    "A famous pianist gives a concert.",
    "Bridging physical space and social distinctions, two men communicate telepathically.",
    "Head of a robust youth changes into that of a mature thinker.",
    "A woman activist in an emotional appeal for political justice.",
    "Two Chinese men converse in an American city.",
    "A large archaic volume reveals a traditional wisdom.",
    "A young gypsy emerges from the woods gazing at far cities.",
    "A tumultuous labor demonstration.",
    "Three fledglings in a nest high in a tree.",
    "A Hindu yogi demonstrates his healing powers.",
    "Dancing couples in a harvest festival.",
    "Children skating over a frozen village pond.",
    "A parade of bathing beauties before large beach crowds.",
    "A new path of realism in experience.",
    "Indians rowing a canoe and dancing a war dance.",
    "A baldheaded man who has seized power.",
    "A Quiver full of arrows.",
    "An old bridge over a beautiful stream is still in constant use.",
    # --- CANCER (90-119) ---
    "On a ship the sailors lower an old flag and raise a new one.",
    "A man on a magic carpet observing vast vistas below him.",
    "An arctic explorer leads a reindeer through icy canyons.",
    "A cat arguing with a mouse.",
    "At a railroad crossing, an automobile is wrecked by a train.",
    "An automobile wrecked by a train.",
    "Game birds feathering their nests.",
    "A group of rabbits dressed in clothes walk as if on parade.",
    "A hen scratching the ground to find nourishment for her progeny.",
    "A tiny nude miss reaching in the water for a fish.",
    "A large diamond in the first stage of the cutting process.",
    "A Chinese woman nursing a baby with a message.",
    "One hand slightly flexed with a very prominent thumb.",
    "A very old man facing a vast dark space to the northeast.",
    "A group of people who have overeaten and enjoyed it.",
    "A man studying a mandala in front of him.",
    "The unfoldment of multilevel potentialities of any germinal situation.",
    "A hen crossing the road.",
    "A priest performing a marriage ceremony.",
    "Venetian gondoliers giving a serenade.",
    "A prima donna singing.",
    "A young woman awaiting a sailboat.",
    "Meeting of a literary society.",
    "A woman and two men castaways on a small island.",
    "A dark shadow or mantle thrown suddenly over the right shoulder.",
    "Guests are reading in the library of a luxurious home.",
    "A violent storm in a canyon filled with expensive homes.",
    "An Indian girl introduces her white lover to her assembled tribe.",
    "A Muse weighing twins.",
    "A daughter of the American Revolution.",
    # --- LEO (120-149) ---
    "Blood rushes to a man's head as his vital energies are mobilized under the spur of ambition.",
    "An epidemic of mumps.",
    "A man turning his back on his passions teaches from his experience.",
    "An old sea captain rocking himself on the porch of his cottage.",
    "A large camel crossing a vast and forbidding desert.",
    "A fully decorated Christmas tree.",
    "The constellations of stars in the sky.",
    "A Bolshevik propagandist.",
    "A Mermaid.",
    "Early morning dew sparkles as sunlight floods the field.",
    "Children on a swing in a huge oak tree.",
    "An evening party of adults on a lawn illuminated by fancy lanterns.",
    "An old sea captain rocking.",
    "A human soul seeking opportunities for outward manifestation.",
    "A pageant, with its spectacular floats, moves along a street crowded with cheering people.",
    "Storm in a canyon.",
    "A Volunteer church choir singing religious hymns.",
    "A chemist conducts an experiment for students.",
    "A houseboat party.",
    "Zuni Indians perform a ritual to the sun.",
    "Intoxicated chickens dizzily flap their wings trying to fly.",
    "A carrier pigeon fulfilling its mission.",
    "In a circus the bareback rider displays her dangerous skill.",
    "A religious organization succeeds in overcoming the corrupting influence of perverted practices.",
    "A large camel is seen crossing a vast and forbidding desert.",
    "After a heavy storm, a rainbow.",
    "The luminescence of dawn in the eastern sky.",
    "Many little birds on the limb of a large tree.",
    "A man is unmasked at a masquerade.",
    "An unsealed letter.",
    # --- VIRGO (150-179) ---
    "In a portrait, the significant features of a man's head are artistically emphasized.",
    "A large white cross dominates the landscape.",
    "Two guardian angels.",
    "Black and white children play together happily.",
    "A man becoming aware of nature spirits and normally unseen spiritual agencies.",
    "A merry-go-round.",
    "A harem.",
    "A five-year-old child takes a first dancing lesson.",
    "An expressionist painter at work.",
    "Two heads looking out and beyond the shadows.",
    "A boy molded in his mother's aspirations for him.",
    "After the wedding, the groom snatches the veil away from his bride.",
    "A powerful statesman overcoming a state of political hysteria.",
    "An aristocratic family tree.",
    "A fine lace handkerchief, heirloom from valorous ancestors.",
    "In the zoo, children are brought face to face with an orangutan.",
    "A volcanic eruption.",
    "A ouija board.",
    "A swimming race.",
    "A caravan of cars headed for the West Coast.",
    "Girls' basketball team.",
    "A royal coat of arms enriched with precious stones.",
    "A lion tamer displays his skill and character.",
    "Mary and her white lamb.",
    "A flag at half-mast.",
    "A boy with a censer serves the priest near the altar.",
    "A group of aristocratic ladies meet ceremonially at a court's function.",
    "A bald-headed man who has seized power dominates a state.",
    "A seeker after occult knowledge is reading an ancient scroll by candlelight.",
    "Having an urgent task to complete, a man doesn't look to any distractions.",
    # --- LIBRA (180-209) ---
    "In a collection of perfect specimens of many biological forms, a butterfly displays the beauty of its wings.",
    "The transmutation of the fruits of past experiences.",
    "The dawn of a new day reveals everything changed.",
    "Around a campfire a group of young people sit in spiritual communion.",
    "A man revealing to his students the foundation of an inner knowledge.",
    "The ideals of a man abundantly crystallized.",
    "A woman feeding chickens and protecting them from the hawks.",
    "A blazing fireplace in a deserted home.",
    "Three 'old masters' hanging on the wall of a special room in an art gallery.",
    "Having passed through narrow rapids, a canoe reaches calm waters.",
    "A professor peering over his glasses at his students.",
    "Miners are surfacing from a deep coal mine.",
    "Children blowing soap bubbles.",
    "In the heat of the noon hour, a man takes a siesta.",
    "Circular paths.",
    "After a storm, a boat landing stands in need of reconstruction.",
    "A retired sea captain watches ships entering and leaving the harbor.",
    "Two men placed under arrest give an accounting for their acts.",
    "A gang of robbers in hiding.",
    "A rabbi performing his duties.",
    "A crowd upon the beach.",
    "A child giving birds a drink at a fountain.",
    "Chanticleer's voice heralds the rising sun with exuberant authority.",
    "A butterfly with a third wing on its left side.",
    "Information in the symbol of an autumn leaf.",
    "An eagle and a large white dove change into each other.",
    "An airplane sails, high in the clear sky.",
    "A man in the midst of brightening influences.",
    "Humanity seeking to bridge the span of knowledge.",
    "Three mounds of knowledge on a philosopher's head.",
    # --- SCORPIO (210-239) ---
    "A sightseeing bus filled with tourists.",
    "A broken bottle and spilled perfume.",
    "A man and a woman, having withdrawn from heavy social involvement.",
    "A youth holds a lighted candle in a devotional ritual.",
    "A massive rocky shore resists the pounding of the sea.",
    "A gold rush tears men away from their native soil.",
    "Deep-sea divers.",
    "A calm lake bathed in moonlight.",
    "A dentist at work.",
    "A fellowship supper reunites old comrades.",
    "A drowning man is being rescued.",
    "An embassy ball.",
    "An inventor performs a laboratory experiment.",
    "Telephone linemen at work installing new connections.",
    "Children playing around five mounds of sand.",
    "A girl's face breaking into a smile.",
    "A woman filled with her own spirit is the father of her own child.",
    "A path through woods brilliant with multicolored splendor.",
    "A parrot repeats the conversation he has overheard.",
    "A woman draws away two dark curtains closing the entrance to a sacred pathway.",
    "Obeying his conscience, a soldier resists orders.",
    "Hunters shooting wild ducks.",
    "A rabbit metamorphoses into a nature spirit.",
    "After having heard an inspired individual deliver his 'Sermon on the Mount', crowds return home.",
    "An X-ray photograph.",
    "Indians making camp after moving into a new territory.",
    "A military band marches noisily on through the city streets.",
    "The king of the fairies approaching his domain.",
    "An Indian squaw pleading to the chief for the lives of her children.",
    "Children in Halloween costumes indulge in various pranks.",
    # --- SAGITTARIUS (240-269) ---
    "Retired army veterans gather to reawaken old memories.",
    "The ocean covered with whitecaps.",
    "Two men playing chess.",
    "A little child learning to walk with the encouragement of her parents.",
    "An old owl sits alone on the branch of a large tree.",
    "A game of cricket.",
    "A woman assists underground rescue work.",
    "Within the depths of the earth, new elements are being formed.",
    "A mother leads her small child step by step up a steep stairway.",
    "A theatrical representation of a golden-haired goddess of opportunity.",
    "The lamp of physical enlightenment at the left temple.",
    "A flag that turns into an eagle that crows.",
    "A widow's past is brought to light.",
    "The Great Pyramid and the Sphinx.",
    "The ground hog looking for its shadow on Ground Hog Day.",
    "Sea gulls fly around a ship looking for food.",
    "An Easter sunrise service draws a large crowd.",
    "Tiny children in sunbonnets.",
    "Pelicans menaced by the behavior and refuse of men seek safer areas for nesting.",
    "In an old-fashioned northern village men cut ice from a frozen pond for use in summer.",
    "A child and a dog wearing borrowed eyeglasses.",
    "A Chinese laundry.",
    "A group of immigrants as they fulfill the requirements of entrance into a new country.",
    "A bluebird perched on the gate of a cottage.",
    "A chubby boy on a hobbyhorse.",
    "A flag bearer in a battle.",
    "A sculptor at his work.",
    "An old bridge over a beautiful stream.",
    "A fat boy mowing the lawn of his house.",
    "The Pope blessing the faithful.",
    # --- CAPRICORN (270-299) ---
    "An Indian chief claims power from the assembled tribe.",
    "Three rose windows in a Gothic church.",
    "A human soul, in its eagerness for new experience, seeks embodiment.",
    "A group of people outfitting a large canoe at the start of a journey.",
    "Indians on the warpath. While some men row a well-filled canoe, others in it perform a war dance.",
    "Ten logs lie under an archway leading to darker woods.",
    "A veiled prophet speaks, seized by the power of a God.",
    "In a sun-lit home domesticated birds sing joyously.",
    "An angel carrying a harp.",
    "An albatross feeding from the hand of a sailor.",
    "A large group of pheasants on a private estate.",
    "An illustrated lecture on natural science reveals little-known aspects of life.",
    "A fire worshiper meditates on the ultimate realities of existence.",
    "An ancient bas-relief carved in granite remains a witness to a long-forgotten culture.",
    "In a hospital, the children's ward is filled with toys.",
    "School grounds filled with boys and girls in gymnasium suits.",
    "A repressed woman finds a psychological release in nudism.",
    "The Union Jack flag flies from a British warship.",
    "A five-year-old child carrying a bag filled with groceries.",
    "A hidden choir is singing during a religious service.",
    "A relay race.",
    "By defeating his negative instincts, a general accepts defeat gracefully.",
    "A soldier receiving two awards for bravery in combat.",
    "A woman entering a convent.",
    "An oriental rug dealer in a store filled with precious ornamental rugs.",
    "A nature spirit dancing in the iridescent mist of a waterfall.",
    "Pilgrims climbing the steep steps leading to a mountain shrine.",
    "A large aviary.",
    "A woman reading tea leaves.",
    "A secret meeting of men responsible for executive decisions in world affairs.",
    # --- AQUARIUS (300-329) ---
    "An old adobe mission in California.",
    "An unexpected thunderstorm.",
    "A deserter from the navy.",
    "A Hindu healer glows with a mystic healing power.",
    "A council of ancestors is seen implementing the efforts of a young leader.",
    "A masked figure performs ritualistic acts in a mystery play.",
    "A child is seen being born out of an egg.",
    "Beautifully gowned wax figures on display.",
    "A flag is seen turning into an eagle.",
    "A popularity that proves to be fleeting.",
    "During a silent hour, a man receives a new inspiration which may change his life.",
    "On a vast staircase stand people of different types, graduated upward.",
    "A barometer.",
    "A train entering a tunnel.",
    "Two lovebirds sitting on a fence and singing happily.",
    "A big businessman at his desk.",
    "A watchdog stands guard, protecting his master and his possessions.",
    "A man being unmasked at a masquerade.",
    "A forest fire finally quenched.",
    "A large white dove bearing a message.",
    "A woman disappointed and disillusioned, courageously facing a seemingly empty life.",
    "A rug placed on the floor for children to play.",
    "A big bear sitting down and waving all its paws.",
    "An ancient pottery bowl filled with fresh violets.",
    "A butterfly with the right wing more perfectly formed.",
    "A garage man testing a car's battery with a hydrometer.",
    "An ancient pottery bowl filled with violets.",
    "A tree felled and sawed to ensure a supply of wood for the winter.",
    "A butterfly emerging from a chrysalis.",
    "Deeply rooted in the past of a very ancient culture, a spiritual brotherhood.",
    # --- PISCES (330-359) ---
    "In a crowded marketplace farmers and tradespeople display a variety of products.",
    "A squirrel hiding from hunters.",
    "A petrified forest.",
    "An illuminated crowd has been electrified by the address of a dynamic speaker.",
    "A heavy traffic on a narrow isthmus linking two seaside resorts.",
    "A church bazaar.",
    "Illuminated by a shaft of light, a large cross lies on rocks.",
    "A girl blowing a bugle.",
    "A jockey spurs his horse, intent on outdistancing his rivals.",
    "An aviator pursues his journey, flying through ground-obscuring clouds.",
    "Men traveling a narrow path, seeking illumination.",
    "In the sanctuary of an occult brotherhood, newly initiated members are being examined and their characters tested.",
    "An ancient sword, used in many battles, is displayed in a museum.",
    "A lady wrapped in a large stole of fox fur.",
    "An officer instructing his men before a simulated assault.",
    "In the quiet of his study a creative individual experiences a flow of inspiration.",
    "An Easter parade.",
    "In a huge tent, a famous revivalist conducts his meeting.",
    "A master instructing his disciple.",
    "A table set for an evening meal.",
    "A little white lamb, a child, and a Chinese servant.",
    "A man bringing down a new law from Sinai.",
    "A 'materializing' medium giving a séance.",
    "An inhabited island.",
    "The purging of the priesthood.",
    "Watching the very thin moon crescent in the west, on a clear evening.",
    "The harvest moon illumines a clear autumnal sky.",
    "A fertile garden under the full moon.",
    "Light breaking into many colors as it passes through a prism.",
    "A majestic rock formation resembles a face idealized by a boy."
]

# ----------------------------------------------------------------
# Decan-Tarot Mapping (from the Tech Spec)
# Maps (sign_index, decan_index) -> Tarot Minor Arcana card
# sign_index: 0=Aries ... 11=Pisces
# decan_index: 0=Decan1(0-10°), 1=Decan2(10-20°), 2=Decan3(20-30°)
# ----------------------------------------------------------------
DECAN_TAROT_MAP = {
    # Aries (Wands)
    (0, 0): "2 of Wands",    (0, 1): "3 of Wands",    (0, 2): "4 of Wands",
    # Taurus (Pentacles)
    (1, 0): "5 of Pentacles",(1, 1): "6 of Pentacles",(1, 2): "7 of Pentacles",
    # Gemini (Swords)
    (2, 0): "8 of Swords",   (2, 1): "9 of Swords",   (2, 2): "10 of Swords",
    # Cancer (Cups)
    (3, 0): "2 of Cups",     (3, 1): "3 of Cups",     (3, 2): "4 of Cups",
    # Leo (Wands)
    (4, 0): "5 of Wands",    (4, 1): "6 of Wands",    (4, 2): "7 of Wands",
    # Virgo (Pentacles)
    (5, 0): "8 of Pentacles",(5, 1): "9 of Pentacles",(5, 2): "10 of Pentacles",
    # Libra (Swords)
    (6, 0): "2 of Swords",   (6, 1): "3 of Swords",   (6, 2): "4 of Swords",
    # Scorpio (Cups)
    (7, 0): "5 of Cups",     (7, 1): "6 of Cups",     (7, 2): "7 of Cups",
    # Sagittarius (Wands)
    (8, 0): "8 of Wands",    (8, 1): "9 of Wands",    (8, 2): "10 of Wands",
    # Capricorn (Pentacles)
    (9, 0): "2 of Pentacles",(9, 1): "3 of Pentacles",(9, 2): "4 of Pentacles",
    # Aquarius (Swords)
    (10, 0): "5 of Swords",  (10, 1): "6 of Swords",  (10, 2): "7 of Swords",
    # Pisces (Cups)
    (11, 0): "8 of Cups",    (11, 1): "9 of Cups",    (11, 2): "10 of Cups",
}


def get_sabian_symbol(degree: float) -> str:
    """
    Returns the Sabian Symbol for a given ecliptic degree (0-359.99).
    Sabian symbols are traditionally 1-indexed per sign degree,
    but we use 0-based index into our 360-entry list.

    Args:
        degree: Ecliptic longitude (0.0 to 359.99)

    Returns:
        The Sabian Symbol phrase for that degree.
    """
    # ! Important: Sabian convention rounds UP to the next whole degree
    # e.g., 15.3° Aries = Symbol for Aries 16° = index 15
    idx = int(degree) % 360
    return SABIAN_SYMBOLS[idx]


def get_decan_tarot(degree: float) -> str:
    """
    Returns the Tarot Minor Arcana card for a given ecliptic degree.
    Uses the Decan system: each sign (30°) is split into three 10° decans.

    Args:
        degree: Ecliptic longitude (0.0 to 359.99)

    Returns:
        The Tarot card name (e.g., "3 of Wands").
    """
    sign_index = int(degree / 30)
    degree_in_sign = degree % 30
    decan_index = int(degree_in_sign / 10)
    return DECAN_TAROT_MAP.get((sign_index, decan_index), "Unknown Card")
